### ISSUE TITLE
XUL: Dynamic tree creation doesn`t work properly

### ISSUE THREAD

**Issue by sergeev-av** [clientside/amplesdk#117]
I try to create tree dynamicly via javascript. All children are appending at the bottom of a tree, no matter where I try to add them.
I pulled up "My Folders" node in "Mail Client" application at the top of "Folders" column.  "Folder-custom" children appended into "Spam" folder.

Here is example: http://pastebin.com/3Pwc0bWB

**Comment by h6w** [comment]
My apologies for the delay over the festive season.

I have reworked your example to confirm the problem here: http://pastebin.com/D1yS6pdy

**Comment by h6w** [comment]
This problem appears to be as a result of not specifying a "primary" column.

For example, I modified the previous example to this: http://pastebin.com/diff.php?i=30nEJgiN

Adding a primary="true" attribute made it all work.

Therefore, this bug occurs because we're not assuming the first column is primary when none are specified.

**Comment by sergeev-av** [comment]
Thanks! It works!

**Comment by sergeev-av** [comment]
Here is another example: http://pastebin.com/9kHmN686
I put 3 items into tree. 2 of them are folders supposed to have items and 1 is file. Folders contain treechildren element and have onclick event set. Onclick appends another 3 items into clicked(opening) Folder. I alert tree.toXML() after loading items to be sure adding items into right place.

Items are added at the bottom of tree after "File1" item after cliking/opening Folder2.
Supposed: items are added into Folder2 item.

**Comment by h6w** [comment]
Hello.  I've corrected your example in a number of ways:
1) The type of the style file has to be "text/ample+css" and not just "text/css".  This causes the css to be parsed properly by PHP before sending it to your browser.  This was the primary problem in your example.
2) Additionally, adding in a css clause to push body to the edges of the window overcomes a small cosmetic problem with most browsers. (I put this in the previous example, too.)

I've put the changes to your example here:  http://pastebin.com/diff.php?i=bEaKW70N

**Comment by sergeev-av** [comment]
1) I think developers should make changes in SDK examples, because line with "text/css" was taken from example.
2) Thanks.

-----Original Message-----

**Comment by h6w** [comment]
Can you point out which example contains this, please?

**Comment by sergeev-av** [comment]
Here they are:
apps\imclient\index.html
apps\mail\index.html
apps\rss\index.html
langs\xul\index.html
langs\xul\xul.html
langs\chart\index.html
langs\xhtml\forms.html
langs\xmlschema\index.html
modules\history\index.html

**Comment by h6w** [comment]
Hello again,

I have checked all the files you have listed.  They all contain the 
'text/ample+css' type and have done since October 2010.

Is it possible you might have an out of date version of amplesdk?

For proof see the links below which match the files you mention with the 
appropriate line highlighted.

https://github.com/clientside/amplesdk/blob/master/examples/applications/imclient/index.html#L8
https://github.com/clientside/amplesdk/blob/master/examples/applications/mail/index.html#L8
https://github.com/clientside/amplesdk/blob/master/examples/applications/rss/index.html#L8
https://github.com/clientside/amplesdk/blob/master/examples/languages/xul/index.html#L7
https://github.com/clientside/amplesdk/blob/master/examples/languages/xul/xul.html#L8
https://github.com/clientside/amplesdk/blob/master/examples/languages/chart/index.html#L7
https://github.com/clientside/amplesdk/blob/master/examples/languages/xhtml/forms.html#L7
https://github.com/clientside/amplesdk/blob/master/examples/languages/xmlschema/index.html#L8
https://github.com/clientside/amplesdk/blob/master/examples/modules/history/index.html#L7

**Comment by sergeev-av** [comment]
Hello.

Stable version here http://www.amplesdk.com/download/prepare?releases/ample-0.9.3.zip(12th June, 2011) doesn`t contain this changes. Should I checkout sources from github instead downloading stable version?

**Comment by h6w** [comment]
Hmmm, you are correct.  The version from the website is different to the 0.9.3 tag in github.   I'll defer this one to @ilinsky .   For now, I'd suggest checking out sources from github, yes.

**Comment by h6w** [comment]
See issue #123.   @sergeev-av, I'd strongly suggest getting the github version.  Generally it's assumed that bug reports are against the development version unless a specific version is specified.   Please close this issue or provide an example that fails under the current code from github.

**Comment by sergeev-av** [comment]
Here are my steps:
1) downloaded repository as zip file(clientside-amplesdk-0.9.3-70-gc6b03ca) from https://github.com/clientside/amplesdk
2) set up mod_rewrite on my apache server
3) started examples from zip file. Success.
4) downloaded your example from here http://pastebin.com/diff.php?i=bEaKW70N
5) started example. Clicked "Folder2". Got this picture http://xmages.net/i/3331377
6) tried example at Opera, Mozilla, IE, Chrome. Failed.

**Comment by ilinsky** [comment]
The mess around use of language stylesheets is now resolved per rev dc52e3718cb28cf1c6dcf9b59e25d8df182dbf74 From now on the source version examples are identical to built examples, as well as stylesheets referenced.
