### ISSUE TITLE
Consider introducing NamedNodeMap and storing attributes as nodes

### ISSUE THREAD

**Issue by ilinsky** [clientside/amplesdk#162]
Analyzie performance (the attribute node objects were not in framework because of performance optimization), and compatibility impact.

**Comment by AmicaNoctis** [comment]
When you want to implement XPath, there is no way to circumvent attribute nodes, but it would be possible to follow a lazy approach. This is my suggestion:
1. Rename the “attributes” property of the “Element” class to “$attributes”, since the current name conflicts with the W3C specs, that “attributes” should be a NamedNodeMap.
2. Create another property “attributes” which holds a special NamedNodeMap containing a reference to the Element, e. g. “this.$ownerElement”.
3. Only when this NamedNodeMap is queried, refer to this.$ownerElement.$attributes and wrap the value as a new instance of Attr and store it in the instance for later lookup retrieval.

This is IMHO the solution with the least performance impact but still sufficient for XPath expressions which return attribute nodes.

In my fork i did it a bit quick and dirty and mixed the minimum required functionality of NamedNodeMap into the existing “attributes” hashmap. But this is risky because of potential name collisions, which might be very hard to debug or detect in userland code and impossible to work around with foreign XML documents. So, don't follow my example in this, although it works as long as elements have no attributes named “getNamedItem”, “getNamedItemNS” or “hasOwnProperty”.

Just my two cents.

Amica

**Comment by ilinsky** [comment]
Available in master.
