### ISSUE TITLE
$pressable - Feature request

### ISSUE THREAD

**Issue by rkernahan** [clientside/amplesdk#33]
We have $hoverable and $selectable which are frequently useful.
I find myself adding a _press class manually in many widgets (button, checkbox, radio options, slider, lists, etc)
_press is added on mousedown and removed on mouseup and also removed on mouseleave

Do you think its a useful enhancement?

**Comment by ilinsky** [comment]
Look, I think you are talking here about two different interaction patterns - activation and selection, where the first may lead to the second (activating radio button leads to its selection, but activating a regular button does not). There are more UI elements that can be activated compared to whose that can be selected. But the problem here is that different UI elements get activated in different ways, for example: checkbox can be activate with a space bar or with mouse click, a select element in HTML can be "activated" with arrow down button or mouse click etc. Generalizing those activation behaviors is not possible, so this should be left to a specific element rather than to the framework.

Also, take into consideration that $selectable is something weird, and it is used to indicate if the element is text-selectable only. $hoverable is a runtime optiomization - normaly any element that has presentation should be "hoverable" and have :hover pseudo-class applied upon hovering.

Let me know what do you think.

**Comment by rkernahan** [comment]
Thanks for your thoughts. I agree. Having implemented a few more widgets, its clearer to me now that a press pseudoclass at the root of the widget is less useful because the pressing occurs on just a part of the widget (eg. the button of a comboBox, or two buttons in a spinner).
Happy to close this request.
