### ISSUE TITLE
Window management

### ISSUE THREAD

**Issue by invaders-xx** [clientside/amplesdk#65]
I am trying to create a window and append content to the window. looking at the window structure I am looking for tbody class="xul-window--gateway". See the code below :
var window = ample.createElementNS(sXulNS, "xul:window");
ample.get(url,null, function(data){
     var obj = ample.query("tbody.xul-window--gateway",window);
     console.log(obj);
});

obj is empty : what's wrong ?

Thanks in advance

**Comment by clientside** [comment]
It is not possible to access element shadow content (in most cases HTML) from application scripting APIs. ample.query can only traverse the model tree (constructed of XUL, SVG or XHTML elements).

What are you trying to do here otherwise?:
var obj = ample.query("tbody.xul-window--gateway",window);

You can add contents to window by doing following, for example:
window.appendChild(ample.createElementNS(sXulNS, "xul:textbox"))
or:
ample.query(window).append('<xul:textbox xmlns:xul="' + sXulNS + '" />');
or, if you want to load XML content and insert it as children of window:
ample.query(window).load(url);

Please also consider using runtime-dev.js file to be able and get human-readable warnings and errors in development console.

Let me know if you need more assistance

**Comment by invaders-xx** [comment]
ok i understand now. But how do you access a specific object within the window.
I am a jquery user and in jquery you do :
$(window).find('tbody.xul-window--gateway');
So in general how do you access element within an object ?

Thanks in advance,

**Comment by clientside** [comment]
You are not supposed to access "shadow content" - there are intentionally no APIs for that. You should work with model or "host" tree. For example finding all listcell elements in listview: ample.query("xul|listview xul|listcell"), or finding a textbox in window element: ample.query("xul|window xul|textbox.mytextbox").

BTW, what for do you want to access shadow content?

**Comment by invaders-xx** [comment]
for example I want to change behaviour of close button of window because you do a hide(), and I want to destroy the window. I also want to add 2 new button : maximize and minimize.

**Comment by clientside** [comment]
1) I want to change behaviour of close button of window
You should register an event handler for windowhidden event on the instance and do whatever you need in it. For example:
ample.query(".mywindow").bind("windowhidden", function(e) {
e.target.parentNode.removeChild(e.target);
})

2) I also want to add 2 new button : maximize and minimize
This should be done by modifying the implementation of the window element implementation found here: https://github.com/clientside/amplesdk/blob/master/ample/languages/xul/elements/window.js
You can also leave a feature request for adding those new buttons here in the new issue or implement them yourself and ask to pull changes.
